#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#    database: mysql
#  datasource:
#    username: user
#    password: pass
#    url: jdbc:mysql://localhost:3306/JobSearch
