spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: user
      password: pass
      jdbc-url: jdbc:mysql://localhost:3306/JobSearch
